name: CI
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: install poetry
        run: |
          pip install poetry
          poetry install
          ls -la
          source .venv/bin/activate
      # - name: Run Tests
      #   run: |
      #     coverage run -m pytest
