name: CI
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: install poetry
        run: |
          pip install poetry
          poetry install
      - name: Run Tests
        run: |
          python -m coverage run -m pytest
