name: CI
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: install poetry
        run: |
          pip install poetry
          poetry install
          pip freeze
        env:
          POETRY_VIRTUALENVS_CREATE: false
